---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/dotmesh-io/dotscience-slack-plugin

steps:
- name: build and test
  pull: default
  image: golang
  environment:
    GO111MODULE: off
  commands:
  - make install
  - make test

- name: publish-dockerhub
  pull: default
  image: plugins/docker
  settings:
    auto_tag: true
    repo: dotscience/dotscience-slack-plugin
    password:
      from_secret: hub_password
    username:
      from_secret: hub_username